# disable sudo to use container based build
sudo: false
# Enabling test on Linux and OS X
os:
  - linux

# Use Build Matrix to do lint and build seperately
env:
  matrix:
    - TASK=lint LINT_LANG=cpp
    - TASK=lint LINT_LANG=python
    - TASK=doc
    - TASK=build CXX=g++
    - TASK=python CXX=g++
    - TASK=python3 CXX=g++
    - TASK=python_naive CXX=g++
    - TASK=python_perdev CXX=g++
    - TASK=cpp_unittest CXX=g++

# dependent apt packages
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - wget
      - git
      - libcurl4-openssl-dev
      - unzip
      - libatlas-dev
      - libopencv-dev
      - gcc-4.8
      - g++-4.8
      - clang
      - python-numpy
      - python-nose
      - python3-numpy
      - python3-dev
      - python3-nose


before_install:
  - export NVCC_PREFIX=${HOME}
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - scripts/build_dmlc.sh
  - export TRAVIS=dmlc-core/scripts/travis
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/python
  - source ${TRAVIS}/travis_setup_env.sh


install:
  - pip install cpplint pylint graphviz --user `whoami`


script:
  - scripts/travis_script.sh


before_cache:
  - ${TRAVIS}/travis_before_cache.sh

cache:
  directories:
    - ${HOME}/.cache/usr


notifications:
# Emails are sent to the committer's git-configured email address by default,
  email:
    on_success: change
    on_failure: always
  slack: dmlc:NmroCzntCiWOuxUZpii40USd
